In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline, splrep, splev
from scipy.interpolate import BSpline, PPoly
from compute_spline_boundary import *




  function demo_00_splinegauss_2025

 --------------------------------------------------------------------------
  Object:
  This demo shows how the boundary is recovered by splines.
 
  In this example, the domain has a non trivial geometry, tracked by 
  cubic splines.
 --------------------------------------------------------------------------
  Important: it requires the Matlab built-in "curve fitting toolbox".
 --------------------------------------------------------------------------
  Example:
 
  >> demo_00_splinegauss_2025
  
  ans =
  
      , 0.0405   -, 0.1500    , 0.1556    , 0.4980
      , 0.0094   -, 0.0286   -, 0.0230    , 0.5441
      , 0.0017   -, 0.0005   -, 0.0520    , 0.5020
     -, 0.0217    , 0.0047   -, 0.0478    , 0.4512
      , 0.0984   -, 0.0605   -, 0.1036    , 0.3863
     -, 0.1283    , 0.2348    , 0.0708    , 0.3207
  
  
  ans =
  
     -, 0.1772    , 0.4582   -, 0.1011    , 0.2383
     -, 0.0085   -, 0.0734    , 0.2838    , 0.4183
      , 0.0245   -, 0.0989    , 0.1115    , 0.6202
      , 0.0179   -, 0.0255   -, 0.0129    , 0.6573
     -, 0.1055    , 0.0280   -, 0.0104    , 0.6367
      , 0.2489   -, 0.2885   -, 0.2709    , 0.5488
 --------------------------------------------------------------------------

In [4]:
#..........................................................................
# Define sample points of the boundary as N x 2 matrix, via the variable
# "vertices".
# The k-th point has coordinates "vertices(k,:)".
# Notice that first and last sample point are equal.
#..........................................................................

vertices= np.array([[ 0.49804687500000   , 0.23832417582418]
    , [0.52148437500000   , 0.29601648351648]
    , [0.55507812500000   , 0.35233516483516]
    , [0.58398437500000   , 0.40315934065934]
    , [0.58242187500000   , 0.42513736263736]
    , [0.56757812500000   , 0.43475274725275]
    , [0.54414062500000   , 0.41826923076923]
    , [0.52226562500000   , 0.38942307692308]
    , [0.49570312500000   , 0.38392857142857]
    , [0.48710937500000   , 0.41552197802198]
    , [0.48945312500000   , 0.47184065934066]
    , [0.49882812500000   , 0.54601648351648]
    , [0.50195312500000   , 0.62019230769231]
    , [0.49257812500000   , 0.64766483516484]
    , [0.47773437500000   , 0.63667582417582]
    , [0.46601562500000   , 0.55975274725275]
    , [0.45039062500000   , 0.47733516483516]
    , [0.45273437500000   , 0.57760989010989]
    , [0.45117187500000   , 0.65728021978022]
    , [0.43085937500000   , 0.67788461538462]
    , [0.41757812500000   , 0.65178571428571]
    , [0.41679687500000   , 0.57074175824176]
    , [0.41445312500000   , 0.48008241758242]
    , [0.40195312500000   , 0.55700549450549]
    , [0.38632812500000   , 0.63667582417582]
    , [0.37304687500000   , 0.64766483516484]
    , [0.36210937500000   , 0.62568681318681]
    , [0.36992187500000   , 0.53640109890110]
    , [0.37695312500000   , 0.44848901098901]
    , [0.34492187500000   , 0.50068681318681]
    , [0.32070312500000   , 0.54876373626374]
    , [0.30195312500000   , 0.55151098901099]
    , [0.29882812500000   , 0.53090659340659]
    , [0.32460937500000   , 0.45398351648352]
    , [0.34570312500000   , 0.40041208791209]
    , [0.34960937500000   , 0.32074175824176]
    , [0.49804687500000   , 0.23832417582418]]);

# Diminish the number of vertices for tests.
vertices = vertices[: :6][:]

vertices = np.array([[0.4980,    0.2383],
                     [0.5441   , 0.4183], 
                     [0.5020  ,  0.6202],
                     [0.4512  ,  0.6573],
                     [0.3863  ,  0.6367],
                     [0.3207  ,  0.5488],
                     [0.4980   , 0.2383]])



spline_parms=np.array([[4 , np.shape(vertices)[0]]]);
spline_type='periodic';

#..........................................................................
# Observation on the code above:
#
# The intention of the user is to define the domain and the spline
# boundary, using sampling points "vertices", "spline_parms", "spline_type".
#
# The domain has as vertices some points of a domain hand-like domain.
#
# In each row of "spline_parms", the first component is the order of the
# spline, while the second component says what sampling points are used.
#
# The cubic spline is periodic in view of "spline_type='periodic'".
#
# In our example,  a curvilinear-spline boundary (s1(t),s2(t)) tracks the
# sampling points and "s1", "s2" are splines of order "4" (e.g. cubic
# splines, since the degree is equal to the order minus 1).
#..........................................................................

X=vertices[:,0]
print('X=',X)
# L = np.shape(spline_parms)[0]
# print(L)
# imax=spline_parms[0,1]
# imin=spline_parms[0,1]
# print(imin, imax)
# tL=np.arange(0,imax)
# print(tL)
Y=vertices[:,1]; # sampling points in each variable
print('Y=',Y)
# Determine the spline boundary via the vectors of splines "Sx" and "Sy".






Sx,Sy= compute_spline_boundary(X,Y,spline_parms,spline_type)


# show coefficients
# print('Sx.c=', type(Sx), Sx[0].c[:,1:-1])
# print('Sy.c=',Sy[0].c[:,1:-1])


print('Sx.c=', type(Sx), Sx[0].c)
print('Sy.c=',Sy[0].c)
Sy[0].c.shape[0]

X= [0.498  0.5441 0.502  0.4512 0.3863 0.3207 0.498 ]
Y= [0.2383 0.4183 0.6202 0.6573 0.6367 0.5488 0.2383]
Sx.c= <class 'list'> [[ 0.04048  0.00932  0.00174 -0.02168  0.09838 -0.12824]
 [-0.14996 -0.02852 -0.00056  0.00466 -0.06038  0.23476]
 [ 0.15558 -0.0229  -0.05198 -0.04788 -0.1036   0.07078]
 [ 0.498    0.5441   0.502    0.4512   0.3863   0.3207 ]]
Sy.c= [[-0.17728 -0.00846  0.02442  0.01788 -0.10554  0.24898]
 [ 0.45838 -0.07346 -0.09884 -0.02558  0.02806 -0.28856]
 [-0.1011   0.28382  0.11152 -0.0129  -0.01042 -0.27092]
 [ 0.2383   0.4183   0.6202   0.6573   0.6367   0.5488 ]]


4